### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by JamesIves**
**Description**
> Provide a description of what your changes do.

🔴 **Version 3** 🔴 

Migrates the action to use JavaScript instead of bash. There's a few breaking changes here.

- The action will no longer create a `CNAME` file for you automatically.
- The action will no longer run a build script for you.
- You must use the `with` key instead of `env` in your workflow.

With that comes some improvements:

- The action should now deploy much faster.
- It will keep track of your commit history.
- It now utilizes `with` instead of `env`.
- The action can now be properly unit tested. 

I'm currently in the process of finishing this up (mostly just writing tests), but if you'd like to get an early look at this you can point your `workflow.yml` file to `JamesIves/github-pages-deploy-action@beta4` to test it out. 

**Testing Instructions**
> Give us step by step instructions on how to test your changes.

I'll write a proper migration guide when I do the release but here's a quick run down.

* Add a deployment step in your `workflow.yml` file that builds your project. This should occur after checkout, and before this action runs.
* Change `env` to `with`.
* Once the deployment is complete, manually commit a `CNAME` file if you're using a custom domain. You can also safely commit a `.nojekyll` file if need be too.

**Additional Notes**
> Anything else that will help us test the pull request.

Please feel free to flag any issues in this PR.

Closes issue #36 #37 #38

### CODE REVIEW

**Comment by JacksonMaxfield** [comment]
Clarification:

> Once the deployment is complete, manually commit a CNAME file if you're using a custom domain. You can also safely commit a .nojekyll file if need be too.

From this I would assume you mean the workflow syntax would be something like:
1. setup tasks
2. install task
3. build task
4. v3 deploy task
5. commit `.nojekyll` task

**Comment by JamesIves** [comment]
Step 5 would only need to occur once

**Comment by JacksonMaxfield** [comment]
Ahhh right, because git history is now maintained. 👍

**Comment by JamesIves** [comment]
Wrapping up the last couple tests on this tomorrow and then this should be ready to roll.

**Comment by JamesIves** [comment]
Alright! I've finalized most of the details and I'm ready for some people to give this a try. I'd love to push this up before I fly to San Francisco for Chrome Dev Summit.

You can try the beta out using the following: `JamesIves/github-pages-deploy-action@releases/v3-beta`. Let me know if you spot any issues.

**Pull request merged**
