### PR TITLE
Stop checking out workspace

### PR DESCRIPTION
**Pull request by Pike**
**Description**

This PR removes all the functionality and options that relate to the check-out of the workspace. This removes `BASE_BRANCH` to begin with, but also `LFS` and `PRESERVE`. LFS should be handled by the source check-out, and as we're not switching to `BASE_BRANCH` anymore, `PRESERVE` lost its purpose.

**Testing Instructions**
The unit tests pass, and the number of call changes in each commit made sense to me. I'm leaning towards rebasing my PR #505 on top of this one (including an added `DRY_RUN`) before merging, so that we don't have to do integration testing on `dev`.

**Additional Notes**

This is a follow up to our conversation in #508

### CODE REVIEW

**Comment by Pike** [comment]
I've created an incremental PR for the dry-run option in https://github.com/Pike/github-pages-deploy-action/pull/1.

**Comment by JamesIves** [comment]
Thanks! I'll take a look at these in the morning.

**Review by JamesIves — APPROVED** [review]
This looks great! I think the next step is getting this stuff into the version 4 branch so we can get some more testing on this. 

I will get stuff organized and merge this later this week.

**Comment by JamesIves** [comment]
Merged - also added a discussion for v4 related changes here: https://github.com/JamesIves/github-pages-deploy-action/discussions/524

**Pull request merged**
