### PR TITLE
fix issue #866 - upgrading to typescript 4.4.3

### PR DESCRIPTION
**Pull request by lucassabreu**
## Description

related to #866

Just fixed build error because of the unknown type of the errors on catch.

I fixed creating a new function `extractErrorMessage` that checks possible types and extract the message according 

## Testing Instructions

No behavior changes were made.

### CODE REVIEW

**Comment by JamesIves** [comment]
Hey @lucassabreu - thanks for the PR!

I just ran the test suite and it [looks like this is flagging on e.message](https://github.com/JamesIves/github-pages-deploy-action/pull/896/checks?check_run_id=3801675126).

**Comment by lucassabreu** [comment]
@JamesIves i am still trying to fix this error, i will try a little bit more today, but with have an ideia of what it may be send me a reply

```
 FAIL  __tests__/main.test.ts
  main
    ✕ should run through the commands (4 ms)
    ✓ should run through the commands and succeed (2 ms)
    ✓ should throw if an error is encountered (1 ms)

  ● main › should run through the commands

    expect(jest.fn()).toBeCalledTimes(expected)

    Expected number of calls: 14
    Received number of calls: 13

      50 |     })
      51 |     await run(action)
    > 52 |     expect(execute).toBeCalledTimes(14)
         |                     ^
      53 |     expect(rmRF).toBeCalledTimes(1)
      54 |     expect(exportVariable).toBeCalledTimes(1)
      55 |   })

      at __tests__/main.test.ts:52:21
      at fulfilled (__tests__/main.test.ts:5:58)
```

**Comment by lucassabreu** [comment]
nevermind what i just said, looks to be a problem on my machine, i enabled actions on the fork e running the tests the error stop happening

**Comment by JamesIves** [comment]
Thank you!

**Pull request merged**
