### PR TITLE
Use $BASE_BRANCH instead of master

### PR DESCRIPTION
**Pull request by jaiselrahman**
**Description**

Use $BASE_BRANCH instead of master in git subtree command

### CODE REVIEW

**Comment by jaiselrahman** [comment]
`master` branch gets deleted if $BASE_BRANCH is set to `master`

```
Deploying to GitHub...
[src 3c4b337] Deploying to master - 16:36:25
 8 files changed, 21 insertions(+)
 create mode 100644 dist/css/app.1180ca5c.css
 create mode 100644 dist/favicon.ico
 create mode 100644 dist/img/logo.82b9c7a5.png
 create mode 100644 dist/index.html
 create mode 100644 dist/js/app.eb5dcca5.js
 create mode 100644 dist/js/app.eb5dcca5.js.map
 create mode 100644 dist/js/chunk-vendors.80d27098.js
 create mode 100644 dist/js/chunk-vendors.80d27098.js.map

-  Building for production...
1/1 (0)
No new revisions were found
To https://github.com/jaiselrahman/jaiselrahman.github.io.git
 - [deleted]         master
Deployment succesful!

### SUCCEEDED Deploy to master 16:36:32Z (1m7.809s)
```

**Comment by JamesIves** [comment]
Thanks for the pull request! I'll push up a new release with this change.

Cheers

**Comment by JamesIves** [comment]
Thanks for the pull request!

`$BASE_BRANCH` should default to `master`, can you push up a change so that's the default behavior if the variable doesn't exist?

**Comment by jaiselrahman** [comment]
Fixed, Now `$BASE_BRANCH` will default to `master`

**Comment by JamesIves** [comment]
Perfect, thank you!

**Pull request merged**
