### PR TITLE
Unsets Persisted Credentials

### LINKED ISSUE #507: Strip Git of baked config values prior to deployment
Please use the discussion thread here: https://github.com/JamesIves/github-pages-deploy-action/discussions/506

### PR DESCRIPTION
**Pull request by JamesIves**
### Description

This PR resolves an issue with persisted-credentials from the `actions/checkout` step. Before we were instructing users to always set `persist-credentials: false` in another action, which was quite confusing to a lot of users. This was necessary because it bakes the authentication into the git configuration.

This issue resolves #507 #506 

With this change we check to ensure the user is running in a CI setting and _not_ using SSH. If so, we strip the key that is set by `actions/checkout`, `http.https://github.com/.extraheader`.

---

### Testing Instructions

* You can test this in a previous version by setting a repository-name field with an applicable access token *without* setting `persist-credentials` to `false` in `actions/checkout`. You'll get an error saying it does not have permission because it defaults to the configuration used in the Git config which will attempt to use the GitHub token and not the PAT.
* Run `releases/v4-beta`, don't set `persist-credentials`, it will deploy without issue.
* Do the same _without_ persisted credentials, it will hit the catch case and continue without unsetting the config and breaking the build.

---

### Additional Notes

The last issue which needs finishing before v4 can go live is #586 which I'm struggling to debug. The art assets are also not finalized, and will be done tonight.

### CODE REVIEW

**Comment by JamesIves** [comment]
CC: @Pike

**Review by Pike — APPROVED** [review]
Looks good to me.

It's a bit unfortunate to dive so deep under the hood, but I don't have a better idea right now.

**Comment by JamesIves** [comment]
Yeah I don't feel good about this change, but I'm not sure what the best way is to manage user expectations here. There's a thread about this here which may reveal some better ideas: https://github.com/actions/checkout/issues/162

It seems like it's possible to use credential manager and Git will always prefer it over the `.extraheader` token. This may be better as the deployment step is usually the last item in the workflow(?)

**Comment by Pike** [comment]
I found the same conversation ;-)

It also mentions that the credential manager would be brittle. Which may or may not be an issue for us.

The other idea I have in my head is to only use a worktree if we're re-using auth for in-repo pushes, and to set up a vanilla git repo in all other cases. And to then config in the temporary repo instead of inside the workspace. That would also help workflows that don't check out a top-level repo at all. At this point, that might be more something for post-v4?

**Comment by JamesIves** [comment]
Yeah post v4 for sure, for now I think this change is fine and should handle 99% of use cases. I think I'm going to add an integration test to handle this case so we can keep track of this to ensure that the unsetting doesn't break in later versions of action/checkout.

I'll update the PR before merging.

**Pull request merged**
