### PR TITLE
Lowercase Inputs

### PR DESCRIPTION
**Pull request by JamesIves**
**Description**
> Provide a description of what your changes do.

Lowercases inputs in the README and `constants.ts` file.

**Testing Instructions**
> Give us step by step instructions on how to test your changes.

* Ensure that the variables still work.

**Additional Notes**
> Anything else that will help us test the pull request.

I did not lower case the environment variable export `DEPLOYMENT_STATUS` as it's common for environment variables to be uppercase. But I can probably be convinced to lowercase this too if anyone has a strong opinion.

### CODE REVIEW

**Comment by JamesIves** [comment]
Looks like some branch teardown is needed in the new integration tests 😄

**Comment by Pike** [comment]
Can you rerun the test? Looking at the log, it seems to think that the remote branch doesn't exist, and I wonder if that's a mid-air with an integration test elsewhere or something.

**Review by Pike — COMMENTED** [review]
Want to change `action.yml` as well as the workflows, too?

Re `DEPLOYMENT_STATUS`, is the environment variable offering something that `setOutput` wouldn't? The latter would be lower-case, but I was wondering in general 😉

**Comment by JamesIves** [comment]
Ah yes good point, forgot about those:

* Lowercased all inputs in workflows including `deployment_status`.
* Made the adjustments for the `token` variable.
* Removed `token:` when github_token is used so those are properly tested.
* Switched scheduled integration tests to `releases/v4`
* Removed integration-beta tests in favour of the new PR based integration tests.

**Review by Pike — APPROVED** [review]
lgtm, happy to see the beta test go.

**Pull request merged**
